# Utilisation de Python 3.10
FROM python:3.10-slim

# CORRECTION ICI : On remplace 'libgl1-mesa-glx' par 'libgl1'
RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Définition du dossier de travail
WORKDIR /app

# 1. Installation des dépendances Python
COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt
RUN pip install --no-cache-dir gdown

# 2. Copie du code source
COPY app/ ./app
COPY main.py .

# Création du dossier models
RUN mkdir -p models

# =========================================================
# 3. TÉLÉCHARGEMENT DES MODÈLES DEPUIS GOOGLE DRIVE
# =========================================================

# --- PARTIE 1 & 2 : Vision & OOD ---
RUN gdown --id 1BPnjdgWKumh1PBPFZ1T6_8ntQouYyppH -O models/vision_weights.pth
RUN gdown --id 163lT4lxarRYRneQ8C3ddXuqDuwMfOSq7 -O models/ood_detector.joblib

# --- PARTIE 3 : NLP (DistilBERT) ---
RUN gdown --id 1tYdugwnsiQP9bmtxTNQopda0oLSIGcwz -O models/part3_nlp_weights.pth
RUN gdown --id 1NNbIE7y1kFxPpZ87Afa3eRVPBTfLncVr -O models/part3_classes.json

# --- PARTIE 4 : RAG (Qwen/CLIP/Annoy) ---
RUN gdown --id 1Te1r9O8VuYZUorocz16vesIOEDUy9GzL -O models/part4_rag_index.ann
RUN gdown --id 1qM2Lb_BMvrRvW2jKL2AnTKqkcY-Hft5r -O models/part4_rag_map.json
RUN gdown --id 17Hl93qogOQnKl4uIPX-4ZEwjru7NPrLu -O models/part4_rag_brochure.pkl

# =========================================================

# 4. Configuration Environnement
ENV PYTHONPATH=/app
ENV HF_HUB_OFFLINE=0 
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["python", "main.py"]