# Use an official Python runtime as the parent image
FROM python:3.12.12-slim

# Set the working directory in the container to /app
WORKDIR /project-app

COPY requirements-api.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements-api.txt

# Copy the current directory contents into the container at /app
COPY . /project-app

#Create the directory to store the model
RUN mkdir -p models

# 1. On installe gdown (outil spécialisé pour Google Drive)
RUN pip install --no-cache-dir gdown

RUN gdown --id 1i03Dkl4o5ic-t-v-IfkoA8WXvLkUFehQ -O models/movie_genre_cpu.pt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run mnist_api.py when the container launchess
CMD ["python", "main.py"]